In [1]:
import pandas as pd
from string import punctuation
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
from tensorflow.keras.utils import to_categorical

In [2]:
df=pd.read_csv('C:/Users/user/Desktop/인공지능 개발자 양성과정/Generation_text_lstm/data/ArticlesApril2017.csv')# 파일의 경로
df.head()

abstract                 articleID  articleWordCount  \
0      NaN  58def1347c459f24986d7c80               716   
1      NaN  58def3237c459f24986d7c84               823   
2      NaN  58def9f57c459f24986d7c90               575   
3      NaN  58defd317c459f24986d7c95              1374   
4      NaN  58df09b77c459f24986d7ca7               708   

                                byline documentType  \
0  By STEPHEN HILTNER and SUSAN LEHMAN      article   
1                      By GAIL COLLINS      article   
2               By THE EDITORIAL BOARD      article   
3                    By MICHAEL POWELL      article   
4                         By DEB AMLEN      article   

                                            headline  \
0  Finding an Expansive View  of a Forgotten Peop...   
1                  And Now,  the Dreaded Trump Curse   
2              Venezuela’s Descent Into Dictatorship   
3              Stain Permeates Basketball Blue Blood   
4                          Taking Things for Granted   

                                            keywords  multimedia    newDesk  \
0  ['Photography', 'New York Times', 'Niger', 'Fe...           3    Insider   
1  ['United States Politics and Government', 'Tru...           3       OpEd   
2  ['Venezuela', 'Politics and Government', 'Madu...           3  Editorial   
3  ['Basketball (College)', 'University of North ...           3     Sports   
4                              ['Crossword Puzzles']           3      Games   

   printPage              pubDate         sectionName  \
0          2  2017-04-01 00:15:41             Unknown   
1         23  2017-04-01 00:23:58             Unknown   
2         22  2017-04-01 00:53:06             Unknown   
3          1  2017-04-01 01:06:52  College Basketball   
4          0  2017-04-01 02:00:14             Unknown   

                                             snippet              source  \
0  One of the largest photo displays in Times his...  The New York Times   
1                  Meet the gang from under the bus.  The New York Times   
2  A court ruling annulling the legislature’s aut...  The New York Times   
3  For two decades, until 2013, North Carolina en...  The New York Times   
4  In which Howard Barkin and Will Shortz teach u...  The New York Times   

  typeOfMaterial                                             webURL  
0           News  https://www.nytimes.com/2017/03/31/insider/nig...  
1          Op-Ed  https://www.nytimes.com/2017/03/31/opinion/and...  
2      Editorial  https://www.nytimes.com/2017/03/31/opinion/ven...  
3           News  https://www.nytimes.com/2017/03/31/sports/ncaa...  
4           News  https://www.nytimes.com/2017/03/31/crosswords/...

In [3]:
print('열의 개수: ',len(df.columns))
print(df.columns)

열의 개수:  16
Index(['abstract', 'articleID', 'articleWordCount', 'byline', 'documentType',
       'headline', 'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [4]:
df['headline'].isnull().values.any()  #sum()

False

In [5]:
headline = [] # 리스트 선언
headline.extend(list(df.headline.values)) # 헤드라인의 값들을 리스트로 저장
headline[:5] # 상위 5개만 출력

['Finding an Expansive View  of a Forgotten People in Niger',
 'And Now,  the Dreaded Trump Curse',
 'Venezuela’s Descent Into Dictatorship',
 'Stain Permeates Basketball Blue Blood',
 'Taking Things for Granted']

In [6]:
headline = [n for n in headline if n != "Unknown"] # Unknown 값을 가진 샘플 제거
print('노이즈값 제거 후 샘플의 개수 : {}'.format(len(headline))) # 제거 후 샘플의 개수

노이즈값 제거 후 샘플의 개수 : 831


In [7]:
headline[:5]

['Finding an Expansive View  of a Forgotten People in Niger',
 'And Now,  the Dreaded Trump Curse',
 'Venezuela’s Descent Into Dictatorship',
 'Stain Permeates Basketball Blue Blood',
 'Taking Things for Granted']

In [8]:
def repreprocessing(s):
    s=s.encode("utf8").decode("ascii",'ignore')
    return ''.join(c for c in s 
                  if c not in punctuation).lower() # 구두점 제거와 동시에 소문자화

text = [repreprocessing(x) for x in headline]
text[:5]

['finding an expansive view  of a forgotten people in niger',
 'and now  the dreaded trump curse',
 'venezuelas descent into dictatorship',
 'stain permeates basketball blue blood',
 'taking things for granted']

In [9]:
t = Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기 : %d' % vocab_size)

단어 집합의 크기 : 2422


In [10]:
sequences = list()

for line in text: # 1,214 개의 샘플에 대해서 샘플을 1개씩 가져온다.
    encoded = t.texts_to_sequences([line])[0] # 각 샘플에 대한 정수 인코딩
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

sequences[:11] # 11개의 샘플 출력

[[169, 17],
 [169, 17, 665],
 [169, 17, 665, 367],
 [169, 17, 665, 367, 4],
 [169, 17, 665, 367, 4, 2],
 [169, 17, 665, 367, 4, 2, 666],
 [169, 17, 665, 367, 4, 2, 666, 170],
 [169, 17, 665, 367, 4, 2, 666, 170, 5],
 [169, 17, 665, 367, 4, 2, 666, 170, 5, 667],
 [6, 80],
 [6, 80, 1]]

In [11]:
index_to_word={}
for key, value in t.word_index.items(): # 인덱스를 단어로 바꾸기 위해 index_to_word를 생성
    index_to_word[value] = key

print('빈도수 상위 582번 단어 : {}'.format(index_to_word[582]))

빈도수 상위 582번 단어 : exist


In [12]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 19


In [13]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169
   17]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169  17
  665]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169  17 665
  367]]


In [14]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [15]:
print(X[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169  17]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 169  17 665]]


In [16]:
print(y[:3]) # 레이블

[ 17 665 367]


In [17]:
y = to_categorical(y, num_classes=vocab_size)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [19]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1))
# y데이터를 분리하였으므로 이제 X데이터의 길이는 기존 데이터의 길이 - 1
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
151/151 - 2s - loss: 7.4055 - accuracy: 0.0293
Epoch 2/200
151/151 - 2s - loss: 6.9145 - accuracy: 0.0289
Epoch 3/200
151/151 - 2s - loss: 6.7926 - accuracy: 0.0312
Epoch 4/200
151/151 - 2s - loss: 6.7038 - accuracy: 0.0323
Epoch 5/200
151/151 - 2s - loss: 6.6029 - accuracy: 0.0422
Epoch 6/200
151/151 - 2s - loss: 6.4814 - accuracy: 0.0454
Epoch 7/200
151/151 - 2s - loss: 6.3466 - accuracy: 0.0479
Epoch 8/200
151/151 - 2s - loss: 6.1970 - accuracy: 0.0518
Epoch 9/200
151/151 - 2s - loss: 6.0368 - accuracy: 0.0508
Epoch 10/200
151/151 - 2s - loss: 5.8769 - accuracy: 0.0566
Epoch 11/200
151/151 - 2s - loss: 5.7204 - accuracy: 0.0585
Epoch 12/200
151/151 - 2s - loss: 5.5694 - accuracy: 0.0641
Epoch 13/200
151/151 - 2s - loss: 5.4265 - accuracy: 0.0682
Epoch 14/200
151/151 - 2s - loss: 5.2881 - accuracy: 0.0728
Epoch 15/200
151/151 - 2s - loss: 5.1543 - accuracy: 0.0755
Epoch 16/200
151/151 - 2s - loss: 5.0261 - accuracy: 0.0814
Epoch 17/200
151/151 - 2s - loss: 4.9008 - accura

In [20]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=23, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
    # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [21]:
print(sentence_generation(model, t, 'i', 10))
# 임의의 단어 'i'에 대해서 10개의 단어를 추가 생성

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
i survived a sarin gas attack a zebra and as the


In [22]:
print(sentence_generation(model, t, 'how', 10))
# 임의의 단어 'how'에 대해서 10개의 단어를 추가 생성

how to be mindful when you are angry district are right
